name: tests with tape and check code coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - run: yarn && yarn coverage

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage/coverage.raw.json
          flags: unittests
          fail_ci_if_error: true
